In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드(random seed)를 준다.
torch.manual_seed(1)

In [4]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[3], [5], [7]])

In [9]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True) 
# 가중치 b를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
b = torch.zeros(1, requires_grad=True)
# 가중치 W를 출력
print(W) 
# 가중치 b를 출력
print(b) 


## 현재 가중치 W와 b 둘다 0이므로 현 직선의 방정식은 y = 0 * x + 0d

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [10]:
# 가설 세우기
hypothesis = W * x_train + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [11]:
# 비용함수 선언 / 평균제곱오차 MSE
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(27.6667, grad_fn=<MeanBackward0>)


In [12]:
# 경사하강법의 일종인 SGD 구현 lr == learning rate
optimizer = optim.SGD([W, b], lr=0.001)

In [13]:
# optimizer.zero_grad()를 실행하므로서 미분을 통해 얻은 기울기를 0으로 초기화. 
# 기울기를 초기화해야만 새로운 가중치 편향에 대해서 새로운 기울기를 구할 수 있다.
optimizer.zero_grad()

# cost.backward() 함수를 호출하면 가중치 W와 편향 b에 대한 기울기가 계산된다.
# 비용 함수를 미분하여 gradient 계산
cost.backward()

#  그 다음 경사 하강법 최적화 함수 opimizer의 .step() 함수를 호출하여 
#  인수로 들어갔던 W와 b에서 리턴되는 변수들의 기울기에 학습률(learining rate) 
#  0.001을 곱하여 빼줌으로서 업데이트한다. 
optimizer.step()

In [8]:
x_trainSet = torch.FloatTensor([1,2,3,4,5,6,7,8,9,10])
y_trainSet = torch.FloatTensor([18,25,32,39,46,53,60,67,74,81])

W_2 = torch.zeros(1,requires_grad=True)
b_2 = torch.zeros(1,requires_grad=True)

hypothesis_2 = W_2 * x_trainSet + b_2

cost_2 = torch.mean((hypothesis_2 - y_trainSet) ** 2)

optimizer_2 = optim.SGD([W_2, b_2], lr=0.001)

epochs = 20000

for epoch in range(epochs + 1):
    # 가설 계산
    hypothesis_2 = W_2 * x_trainSet + b_2
    
    # Cost 계산
    cost_2 = torch.mean((hypothesis_2 - y_trainSet) **2)
    
    # cost 로 Hx 개선
    optimizer_2.zero_grad()
    cost_2.backward()
    optimizer_2.step()
    
    # 100번마다 로그출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, W_2.item(), b_2.item(), cost_2.item()
        ))
        
 # 위에 정답은 7x + 11 이었는데,  w= 7, b = 10.998 로 cost 도 0.000001임을 알 수 있다.       

Epoch    0/20000 W: 0.660, b: 0.099 Cost: 2854.500000
Epoch  100/20000 W: 8.346, b: 1.614 Cost: 18.894985
Epoch  200/20000 W: 8.293, b: 2.000 Cost: 17.372295
Epoch  300/20000 W: 8.240, b: 2.371 Cost: 15.972483
Epoch  400/20000 W: 8.189, b: 2.726 Cost: 14.685478
Epoch  500/20000 W: 8.140, b: 3.066 Cost: 13.502174
Epoch  600/20000 W: 8.093, b: 3.392 Cost: 12.414219
Epoch  700/20000 W: 8.048, b: 3.705 Cost: 11.413931
Epoch  800/20000 W: 8.005, b: 4.005 Cost: 10.494231
Epoch  900/20000 W: 7.963, b: 4.293 Cost: 9.648649
Epoch 1000/20000 W: 7.924, b: 4.569 Cost: 8.871189
Epoch 1100/20000 W: 7.886, b: 4.833 Cost: 8.156383
Epoch 1200/20000 W: 7.849, b: 5.087 Cost: 7.499172
Epoch 1300/20000 W: 7.814, b: 5.330 Cost: 6.894916
Epoch 1400/20000 W: 7.781, b: 5.564 Cost: 6.339346
Epoch 1500/20000 W: 7.749, b: 5.787 Cost: 5.828540
Epoch 1600/20000 W: 7.718, b: 6.002 Cost: 5.358901
Epoch 1700/20000 W: 7.688, b: 6.207 Cost: 4.927096
Epoch 1800/20000 W: 7.660, b: 6.404 Cost: 4.530089
Epoch 1900/20000 W: 

True