In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
x_train = [[5.1, 3.5, 1.4, 0.2],
           [4.9, 3.0, 1.4, 0.2],
           [5.8, 2.6, 4.0, 1.2],
           [6.7, 3.0, 5.2, 2.3],
           [5.6, 2.8, 4.9, 2.0]]
y_train = [0, 0, 1, 2, 2]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

print(x_train.shape)
print(y_train.shape)

torch.Size([5, 4])
torch.Size([5])


In [3]:
y_one_hot = torch.zeros(5, 3)
print(y_one_hot)
y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
print(y_one_hot.shape)

# 모델을 선언 및 초기화. 4개의 특성을 가지고 3개의 클래스로 분류. input_dim=4, output_dim=3.
# model = nn.Linear(4, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])


In [4]:
# 모델 초기화
W = torch.zeros((4, 3), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.1)

In [5]:
nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # 가설
    hypothesis = F.softmax(x_train.matmul(W) + b, dim=1) 
    print(f"\nhypothesis : {hypothesis}")
    
    # 비용 함수
    cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
    print(f"cost : {cost}")

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))


Epoch    0/1000 Cost: 1.098612
Epoch  100/1000 Cost: 0.250355
Epoch  200/1000 Cost: 0.165517
Epoch  300/1000 Cost: 0.121844
Epoch  400/1000 Cost: 0.095572
Epoch  500/1000 Cost: 0.078246
Epoch  600/1000 Cost: 0.066053
Epoch  700/1000 Cost: 0.057049
Epoch  800/1000 Cost: 0.050149
Epoch  900/1000 Cost: 0.044702
Epoch 1000/1000 Cost: 0.040301


In [9]:
test = torch.FloatTensor([[5.1,3.5,1.4,0.2]])
test = F.softmax(test.matmul(W) + b, dim=1)
print(test)

tensor([[9.9571e-01, 4.2882e-03, 3.3479e-07]], grad_fn=<SoftmaxBackward0>)


In [4]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4, 3) # Output이 3!

    def forward(self, x):
        return self.linear(x)

In [6]:
model = SoftmaxClassifierModel()
print(model)

SoftmaxClassifierModel(
  (linear): Linear(in_features=4, out_features=3, bias=True)
)


In [7]:
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=0.1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.cross_entropy(prediction, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 2.402718
Epoch  100/1000 Cost: 0.235391
Epoch  200/1000 Cost: 0.157001
Epoch  300/1000 Cost: 0.116306
Epoch  400/1000 Cost: 0.091606
Epoch  500/1000 Cost: 0.075208
Epoch  600/1000 Cost: 0.063612
Epoch  700/1000 Cost: 0.055018
Epoch  800/1000 Cost: 0.048413
Epoch  900/1000 Cost: 0.043189
Epoch 1000/1000 Cost: 0.038960


In [16]:

test_data = torch.FloatTensor([[5.1,3.5,1.4,0.2]])
predic_result = model(test_data)
print(predic_result)

tensor([[ 7.1647,  1.7766, -7.5393]], grad_fn=<AddmmBackward0>)


In [25]:
hy = F.softmax(predic_result, dim=1)
print("예측값(소프트맥스 함수 통과)") 
print(hy)

예측값(소프트맥스 함수 통과)
tensor([[9.9545e-01, 4.5497e-03, 4.0939e-07]], grad_fn=<SoftmaxBackward0>)
